# Release ROS 1 package to Alpine ROS.

name: Alpine ROS 1 release workflow
on:
  workflow_call:
    inputs:
      ros-distro:
        description: "ROS distribution name"
        type: string
        default: noetic
      source-repo-slug:
        description: "Package repository slug"
        type: string
        default: ${{ github.repository }}
      source-branch:
        description: "Package repository source branch"
        type: string
        required: true
      release-ref:
        description: "Repository ref to create release"
        type: string
        required: true
      release-repo-slug:
        description: "Release repository slug to push release data"
        type: string
        default: ${{ github.repository }}-release
      rosdistro-fork-slug:
        description: "Rosdistro repository slug to push PR branches. You need to fork alpine-ros/rosdistro1 beforehand"
        type: string
        default: ${{ github.repository_owner }}/rosdistro1
      dry-run:
        description: "Flag to run in dry-run mode"
        type: boolean
        default: true
      git-user:
        description: "Git user name to commit release data nad rosdistro update"
        type: string
        required: true
      git-email:
        description: "Git email to commit release data nad rosdistro update"
        type: string
        required: true
      repository:
        description: "Repository slug to checkout. Mainly for internal testing"
        type: string
        default: ${{ github.repository }}
      action-ref:
        description: "Git ref of alpine-ros-ci-workflows repository. Mainly for testing"
        type: string
        default: main
    secrets:
      token:
        description: "GitHub Token to push to package release repo and rosdistro1 fork"
        required: true
      token-pr:
        description: "GitHub Token to open PR to rosdistro1. If not set, 'token' will be used"
        required: false

jobs:
  alpine-ros1-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repo-slug }}
          ref: ${{ inputs.release-ref }}
          persist-credentials: false
          fetch-depth: 0
      - name: Setup gitconfig
        env:
          GIT_USER: ${{ inputs.git-user }}
          GIT_EMAIL: ${{ inputs.git-email }}
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"
      - name: Setup netrc
        env:
          TOKEN: ${{ secrets.token }}
          TOKEN_PR: ${{ secrets.token-pr }}
        run: |
          if [ -z "${TOKEN}" ]; then
            echo "token is empty" >&2
            exit 1
          fi
          cat <<EOS >${HOME}/.netrc
          machine github.com
          login git
          password ${TOKEN}
          machine api.github.com
          login git
          password ${TOKEN_PR:-${TOKEN}}
          EOS
      - name: Release
        env:
          ACTION_REF: ${{ inputs.action-ref }}
          ROS_DISTRO: ${{ inputs.ros-distro }}
          SOURCE_REPO_SLUG: ${{ inputs.source-repo-slug }}
          RELEASE_REPO_SLUG: ${{ inputs.release-repo-slug }}
          ROSDISTRO_FORK_SLUG: ${{ inputs.rosdistro-fork-slug }}
          SOURCE_BRANCH: ${{ inputs.source-branch }}
          DRY_RUN: ${{ inputs.dry-run }}
        run: |
          action_dir=$(mktemp -d)
          git clone --depth=1 \
            -b ${ACTION_REF:-main} \
            https://github.com/alpine-ros/alpine-ros-ci-workflows.git ${action_dir}

          key=
          case ${DRY_RUN} in
            false) key=y;;
            true) key=s;;
            *)
              echo "Unknown DRY_RUN value ${DRY_RUN}" >&2
              exit 1
              ;;
          esac

          (yes ${key} || true) | ${action_dir}/scripts/alpine-ros1-release.sh \
            "${ROS_DISTRO}" \
            "${SOURCE_REPO_SLUG}" \
            "${RELEASE_REPO_SLUG}" \
            "${ROSDISTRO_FORK_SLUG}" \
            "${SOURCE_BRANCH}"
