name: ROS package auto release workflow
on:
  workflow_call:
    secrets:
      token:
        required: false

jobs:
  release:
    name: auto-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Detect version and tag
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          manifest=$(find . -name package.xml | head -n1)
          version=$(sed -e ':l;N;$!b l;s/\n/ /g;s|^.*<version>\(.*\)</version>.*|\1|' ${manifest})

          cat <<EOS >${HOME}/.netrc
          machine github.com
          login git
          password ${GITHUB_TOKEN}
          EOS

          if git ls-remote --exit-code origin ${version}; then
            echo "Tag ${version} already exists. Nothing to do."
            exit 0
          fi

          echo "Adding ${version} tag."
          git tag ${version}
          if git push origin ${version}; then
            gh release create ${version} --title "Release ${version}"
          else
            echo "Tag ${version} already exists. Nothing to do."
          fi
