name: ci
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/alpine-ros1-release.yaml
    with:
      source-repo-slug: alpine-ros/sample-ros-pkg
      release-ref: 0.0.4
      release-repo-slug: alpine-ros/sample-ros-pkg-release
      git-user: alpine-ros-bot
      git-email: 214657941+alpine-ros-bot@users.noreply.github.com
      action-ref: ${{ github.head_ref }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
